/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.36).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.jediverse.coruscant.api;

import io.jediverse.coruscant.model.Nodeinfo;
import io.micronaut.core.convert.value.MutableConvertibleValues;
import io.micronaut.http.*;
import io.micronaut.http.annotation.*;
import io.reactivex.Single;
import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.responses.*;

import java.util.Optional;


@Controller
public class NodeinfoApi {

    @Operation(summary = "Returns a compliant nodeinfo response to node info queries.", operationId = "nodeInfoGet", description = "See: https://nodeinfo.diaspora.software/schema.html" , tags = {"nodeinfo"})
    @ApiResponse(responseCode = "200", description = "")
    @Get(value = "/nodeinfo/2.0", produces = { "application/json; profile=http://nodeinfo.diaspora.software/ns/schema/2.0#" })
    public Single<HttpResponse<Nodeinfo>> nodeInfoGet() {
        return Single.fromCallable(() -> new HttpResponse<Nodeinfo>() {
            @Override
            public HttpStatus getStatus() {
                return HttpStatus.OK;
            }

            @Override
            public HttpHeaders getHeaders() {
                return null;
            }

            @Override
            public MutableConvertibleValues<Object> getAttributes() {
                return null;
            }

            @Override
            public Optional<Nodeinfo> getBody() {
                return Optional.of(new Nodeinfo());
            }
        });
    }

}
